# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/System.xdc

# Block Designs: bd/System/System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System}]

# IP: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}]

# IP: bd/System/ip/System_processing_system7_0_axi_periph_0/System_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==System_processing_system7_0_axi_periph_0}]

# IP: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}]

# IP: bd/System/ip/System_axi_fifo_mm_s_0_0/System_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==System_axi_fifo_mm_s_0_0}]

# IP: bd/System/ip/System_xbar_0/System_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xbar_0 || ORIG_REF_NAME==System_xbar_0}]

# IP: bd/System/ip/System_xadc_wiz_0_0/System_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xadc_wiz_0_0 || ORIG_REF_NAME==System_xadc_wiz_0_0}]

# IP: bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_1 || ORIG_REF_NAME==System_axi_gpio_0_1}]

# IP: bd/System/ip/System_axi_timer_0_0/System_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_timer_0_0 || ORIG_REF_NAME==System_axi_timer_0_0}]

# IP: bd/System/ip/System_auto_pc_0/System_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_0 || ORIG_REF_NAME==System_auto_pc_0}]

# XDC: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/System/ip/System_axi_fifo_mm_s_0_0/System_axi_fifo_mm_s_0_0_ooc.xdc

# XDC: bd/System/ip/System_xbar_0/System_xbar_0_ooc.xdc

# XDC: bd/System/ip/System_xadc_wiz_0_0/System_xadc_wiz_0_0_ooc.xdc

# XDC: bd/System/ip/System_xadc_wiz_0_0/System_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_xadc_wiz_0_0 || ORIG_REF_NAME==System_xadc_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_1 || ORIG_REF_NAME==System_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_0_1/System_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_1 || ORIG_REF_NAME==System_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_timer_0_0/System_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_timer_0_0 || ORIG_REF_NAME==System_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_timer_0_0/System_axi_timer_0_0_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_0/System_auto_pc_0_ooc.xdc

# XDC: bd/System/System_ooc.xdc
